### ISSUE TITLE
[BUG] can't open file "config/local_test_db.yaml"

### ISSUE THREAD

**Issue by BILL-ON** [atreeon/easy_orm#6]
I tried setting up a simple dart program to test the package but i got the following error :
```
PathNotFoundException: Cannot open file, path = 'config/local_test_db.yaml' (OS Error: No such file or directory, errno = 2)
```
Here is my main : 
```dart
import 'package:easy_orm_postgres/easy_orm_postgres.dart';
import 'package:easy_orm_postgres/service/SqlResponse.dart';
import 'package:hello/generatedDb/db/Db.dart';
import 'package:hello/generatedDb/models/Organization.dart';

Future<int> main() async {
  try {
    var connection = PostgreSQLConnection('localhost', 5432, 'db_name', username: 'username', password: 'password');
    await connection.open();
    final res = await Db().organization.selectQuery();
    print((res as SqlResponse_Success<List<Organization>>).result);
    connection.close();
    return 0;
  } catch (e) {
    print("error : ${e.toString()}");
    return 84;
  }
}
```

Pubspec.yaml :
 ```
name: hello
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.3

dependencies:
  easy_orm_postgres: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  lints: ^2.0.0
  test: ^1.21.0
```

Dart SDK version: 3.0.3 (stable) (Wed May 31 15:35:05 2023 +0000) on "linux_x64"
I use Ubuntu 22.04
